sudo: required
addons:
  apt:
    update: true
language: scala
before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.7/scripts/travis_setup.sh | bash -x
  - sudo apt-get install python3-dev
install:
  - pyenv install -s 3.6.3
  - pyenv global 3.6.3
  - pip install tensorflow
  - git clone https://github.com/VirtuslabRnD/scalapy.git
  - cd scalapy
  - git checkout 2597f7b23301ddd59067de24d4d3809cf475ae9f
  - sed -i 's/^scalaVersion in ThisBuild := scala213Version$/scalaVersion in ThisBuild := scala212Version; version in ThisBuild ~= (_.replaceFirst("\\\\+[^+]+$", ""))/' build.sbt
  - sbt publishLocal
  - cd ..
script:
  - export JEP_PATH="/opt/python/3.6.3/lib/python3.6/site-packages/jep"
  - export LD_LIBRARY_PATH=$(python3-config --prefix)/lib
  - pip install numpy
  - sbt 'project scalaPyTensorFlowCrossJVM' 'runMain me.shadaj.scalapy.tensorflow.example.Example'
  - sbt 'project scalaPyTensorFlowCrossJVM' 'runMain me.shadaj.scalapy.tensorflow.example.MnistExample'
  - sbt test
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ./publish.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -n "$TRAVIS_TAG" ];            then bash ./publish.sh; fi'
